$users = Get-ChildItem -Path "Registry::HKEY_USERS"
foreach ($user in $users) {
    $userKey = $user.Name
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "{374DE290-123F-4565-9164-39C4925E467B}" -Value "%USERPROFILE%\Downloads"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "AppData" -Value "%USERPROFILE%\AppData\Roaming"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Cache" -Value "%USERPROFILE%\AppData\Local\Microsoft\Windows\INetCache"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Cookies" -Value "%USERPROFILE%\AppData\Local\Microsoft\Windows\INetCookies"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Desktop" -Value "%USERPROFILE%\Desktop"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Favorites" -Value "%USERPROFILE%\Favorites"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "History" -Value "%USERPROFILE%\AppData\Local\Microsoft\Windows\History"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Local AppData" -Value "%USERPROFILE%\AppData\Local"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "My Music" -Value "%USERPROFILE%\Music"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "My Pictures" -Value "%USERPROFILE%\Pictures"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "My Video" -Value "%USERPROFILE%\Videos"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "NetHood" -Value "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Network Shortcuts"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Personal" -Value "%USERPROFILE%\Documents"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "PrintHood" -Value "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Printer Shortcuts"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Programs" -Value "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Recent" -Value "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Recent"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "SendTo" -Value "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\SendTo"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Start Menu" -Value "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Startup" -Value "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
    Set-ItemProperty -Path "Registry::$userKey\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" -Name "Templates" -Value "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Templates"
}